# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins
import numpy
import numpy.typing
import typing
from enum import Enum

class AddNoise:
    r"""
    Augmenter that allows different types of noise injection
    
    Noise types:
    
    - Uniform: Adds uniform noise within the given bounds given through the parameter `bounds`
    
    - Gaussian: Adds gaussian noise with the specified mean and standard deviation according to the corresponding parameters
    
    - Spike: Adds a spike in the series with a random magnitude (in the range specified by `bounds` of the standard deviation of the original time series
    
    - Slope: Adds a linear slope trend to the series with a random slope in the range specified by `bounds`
    """
    name: builtins.str
    probability: builtins.float
    def augment_batch(self, dataset:pyfraug.Dataset, parallel:builtins.bool) -> None:
        r"""
        Augment a whole batch
        
        Parallelized when `parallell` is set
        """
    def augment_one(self, x:numpy.typing.NDArray[numpy.float64]) -> numpy.typing.NDArray[numpy.float64]:
        r"""
        Augment one time series
        
        When called, the augmenter will always augment the series no matter what the probability for this augmenter is
        """
    def set_probability(self, p:builtins.float) -> None:
        r"""
        By setting a probability with this function the augmenter will only augment
        a series in a batch with the specified probability
        """

class AmplitudePhasePerturbation:
    r"""
    Amplitude & Phase Perturbation (APP) augmenter.
    Adds small Gaussian noise to each bin’s magnitude and phase.
    """
    name: builtins.str
    probability: builtins.float
    def augment_batch(self, dataset:pyfraug.Dataset, parallel:builtins.bool) -> None:
        r"""
        Augment a whole batch
        
        Parallelized when `parallell` is set
        """
    def augment_one(self, x:numpy.typing.NDArray[numpy.float64]) -> numpy.typing.NDArray[numpy.float64]:
        r"""
        Augment one time series
        
        When called, the augmenter will always augment the series no matter what the probability for this augmenter is
        """
    def set_probability(self, p:builtins.float) -> None:
        r"""
        By setting a probability with this function the augmenter will only augment
        a series in a batch with the specified probability
        """

class Convolve:
    r"""
    Usage of this augmenter is to convolve time series data with a kernel
    
    The kernel can be flat or Gaussian, and the size of the kernel are the parameters
    
    The convolve operation is applied to each time series in the dataset, and smoothening is achieved
    by averaging the values in the kernel window over the time series data.
    """
    name: builtins.str
    probability: builtins.float
    def augment_batch(self, dataset:pyfraug.Dataset, parallel:builtins.bool) -> None:
        r"""
        Augment a whole batch
        
        Parallelized when `parallell` is set
        """
    def augment_one(self, x:numpy.typing.NDArray[numpy.float64]) -> numpy.typing.NDArray[numpy.float64]:
        r"""
        Augment one time series
        
        When called, the augmenter will always augment the series no matter what the probability for this augmenter is
        """
    def set_probability(self, p:builtins.float) -> None:
        r"""
        By setting a probability with this function the augmenter will only augment
        a series in a batch with the specified probability
        """

class Crop:
    r"""
    Augmenter that crops each series into a random continuous slice of specified `size`
    
    Also known as window slicing
    """
    name: builtins.str
    probability: builtins.float
    def augment_batch(self, dataset:pyfraug.Dataset, parallel:builtins.bool) -> None:
        r"""
        Augment a whole batch
        
        Parallelized when `parallell` is set
        """
    def augment_one(self, x:numpy.typing.NDArray[numpy.float64]) -> numpy.typing.NDArray[numpy.float64]:
        r"""
        Augment one time series
        
        When called, the augmenter will always augment the series no matter what the probability for this augmenter is
        """
    def set_probability(self, p:builtins.float) -> None:
        r"""
        By setting a probability with this function the augmenter will only augment
        a series in a batch with the specified probability
        """

class Dataset:
    r"""
    Holds multiple univariate time series with their labels
    
    Passed to the `augment_batch` function from augmenters
    """
    features: numpy.typing.NDArray[numpy.float64]
    labels: builtins.list[builtins.str]
    def __new__(cls, features:numpy.typing.NDArray[numpy.float64], labels:typing.Sequence[builtins.str]) -> Dataset: ...
    def set_features(self, features:numpy.typing.NDArray[numpy.float64]) -> None: ...
    def set_labels(self, labels:typing.Sequence[builtins.str]) -> None: ...

class Drift:
    r"""
    Drifts the value of a time series by a random value at each point in the series.
    
    The drift is linear between the points, bounded by `max_drift`.
    
    The number of drift points is specified by `n_drift_points`.
    """
    name: builtins.str
    probability: builtins.float
    def augment_batch(self, dataset:pyfraug.Dataset, parallel:builtins.bool) -> None:
        r"""
        Augment a whole batch
        
        Parallelized when `parallell` is set
        """
    def augment_one(self, x:numpy.typing.NDArray[numpy.float64]) -> numpy.typing.NDArray[numpy.float64]:
        r"""
        Augment one time series
        
        When called, the augmenter will always augment the series no matter what the probability for this augmenter is
        """
    def set_probability(self, p:builtins.float) -> None:
        r"""
        By setting a probability with this function the augmenter will only augment
        a series in a batch with the specified probability
        """

class Drop:
    r"""
    Augmenter that drops data points in series
    
    Drops `percentage` % of data points and replaces them with `default`
    
    When omitted `default = 0`
    """
    name: builtins.str
    probability: builtins.float
    def augment_batch(self, dataset:pyfraug.Dataset, parallel:builtins.bool) -> None:
        r"""
        Augment a whole batch
        
        Parallelized when `parallell` is set
        """
    def augment_one(self, x:numpy.typing.NDArray[numpy.float64]) -> numpy.typing.NDArray[numpy.float64]:
        r"""
        Augment one time series
        
        When called, the augmenter will always augment the series no matter what the probability for this augmenter is
        """
    def set_probability(self, p:builtins.float) -> None:
        r"""
        By setting a probability with this function the augmenter will only augment
        a series in a batch with the specified probability
        """

class FrequencyMask:
    r"""
    todo!
    """
    name: builtins.str
    probability: builtins.float
    def augment_batch(self, dataset:pyfraug.Dataset, parallel:builtins.bool) -> None:
        r"""
        Augment a whole batch
        
        Parallelized when `parallell` is set
        """
    def augment_one(self, x:numpy.typing.NDArray[numpy.float64]) -> numpy.typing.NDArray[numpy.float64]:
        r"""
        Augment one time series
        
        When called, the augmenter will always augment the series no matter what the probability for this augmenter is
        """
    def set_probability(self, p:builtins.float) -> None:
        r"""
        By setting a probability with this function the augmenter will only augment
        a series in a batch with the specified probability
        """

class Jittering:
    r"""
    Augmenter that adds white gaussian noise of the specified standard deviation and a mean of 0
    
    A special case of the `AddNoise` augmenter
    """
    name: builtins.str
    probability: builtins.float
    def augment_batch(self, dataset:pyfraug.Dataset, parallel:builtins.bool) -> None:
        r"""
        Augment a whole batch
        
        Parallelized when `parallell` is set
        """
    def augment_one(self, x:numpy.typing.NDArray[numpy.float64]) -> numpy.typing.NDArray[numpy.float64]:
        r"""
        Augment one time series
        
        When called, the augmenter will always augment the series no matter what the probability for this augmenter is
        """
    def set_probability(self, p:builtins.float) -> None:
        r"""
        By setting a probability with this function the augmenter will only augment
        a series in a batch with the specified probability
        """

class Permutate:
    r"""
    Permutate time series
    
    First, slices each series into segments and then rearranges them randomly
    """
    name: builtins.str
    probability: builtins.float
    def augment_batch(self, dataset:pyfraug.Dataset, parallel:builtins.bool) -> None:
        r"""
        Augment a whole batch
        
        Parallelized when `parallell` is set
        """
    def augment_one(self, x:numpy.typing.NDArray[numpy.float64]) -> numpy.typing.NDArray[numpy.float64]:
        r"""
        Augment one time series
        
        When called, the augmenter will always augment the series no matter what the probability for this augmenter is
        """
    def set_probability(self, p:builtins.float) -> None:
        r"""
        By setting a probability with this function the augmenter will only augment
        a series in a batch with the specified probability
        """

class Pool:
    r"""
    Reduces the temporal resolution without changing the length by pooling multiple samples together
    """
    name: builtins.str
    probability: builtins.float
    def augment_batch(self, dataset:pyfraug.Dataset, parallel:builtins.bool) -> None:
        r"""
        Augment a whole batch
        
        Parallelized when `parallell` is set
        """
    def augment_one(self, x:numpy.typing.NDArray[numpy.float64]) -> numpy.typing.NDArray[numpy.float64]:
        r"""
        Augment one time series
        
        When called, the augmenter will always augment the series no matter what the probability for this augmenter is
        """
    def set_probability(self, p:builtins.float) -> None:
        r"""
        By setting a probability with this function the augmenter will only augment
        a series in a batch with the specified probability
        """

class Quantize:
    r"""
    Quantize time series to a level set
    
    The level set is constructed by uniformly discretizing the range of all values in the series
    """
    name: builtins.str
    probability: builtins.float
    def augment_batch(self, dataset:pyfraug.Dataset, parallel:builtins.bool) -> None:
        r"""
        Augment a whole batch
        
        Parallelized when `parallell` is set
        """
    def augment_one(self, x:numpy.typing.NDArray[numpy.float64]) -> numpy.typing.NDArray[numpy.float64]:
        r"""
        Augment one time series
        
        When called, the augmenter will always augment the series no matter what the probability for this augmenter is
        """
    def set_probability(self, p:builtins.float) -> None:
        r"""
        By setting a probability with this function the augmenter will only augment
        a series in a batch with the specified probability
        """

class RandomTimeWarpAugmenter:
    name: builtins.str
    probability: builtins.float
    def augment_batch(self, dataset:pyfraug.Dataset, parallel:builtins.bool) -> None:
        r"""
        Augment a whole batch
        
        Parallelized when `parallell` is set
        """
    def augment_one(self, x:numpy.typing.NDArray[numpy.float64]) -> numpy.typing.NDArray[numpy.float64]:
        r"""
        Augment one time series
        
        When called, the augmenter will always augment the series no matter what the probability for this augmenter is
        """
    def set_probability(self, p:builtins.float) -> None:
        r"""
        By setting a probability with this function the augmenter will only augment
        a series in a batch with the specified probability
        """

class Repeat:
    r"""
    Augmenter that repeats all data rows `n` times
    
    Resource intensive because the data needs to be copied `n` times
    
    Only works with `augment_batch` because the data needs to be cloned
    """
    name: builtins.str
    probability: builtins.float
    def augment_batch(self, dataset:pyfraug.Dataset, parallel:builtins.bool) -> None:
        r"""
        Augment a whole batch
        
        Parallelized when `parallell` is set
        """
    def augment_one(self, x:numpy.typing.NDArray[numpy.float64]) -> numpy.typing.NDArray[numpy.float64]:
        r"""
        Augment one time series
        
        When called, the augmenter will always augment the series no matter what the probability for this augmenter is
        """
    def set_probability(self, p:builtins.float) -> None:
        r"""
        By setting a probability with this function the augmenter will only augment
        a series in a batch with the specified probability
        """

class Resize:
    r"""
    Changes temporal resolution of time series by changing the length
    
    Does not interpolate values!
    """
    name: builtins.str
    probability: builtins.float
    def augment_batch(self, dataset:pyfraug.Dataset, parallel:builtins.bool) -> None:
        r"""
        Augment a whole batch
        
        Parallelized when `parallell` is set
        """
    def augment_one(self, x:numpy.typing.NDArray[numpy.float64]) -> numpy.typing.NDArray[numpy.float64]:
        r"""
        Augment one time series
        
        When called, the augmenter will always augment the series no matter what the probability for this augmenter is
        """
    def set_probability(self, p:builtins.float) -> None:
        r"""
        By setting a probability with this function the augmenter will only augment
        a series in a batch with the specified probability
        """

class Reverse:
    r"""
    Reverses time series
    
    The augmenter turns `[1, 2, 3]` to `[3, 2, 1]`
    """
    name: builtins.str
    probability: builtins.float
    def augment_batch(self, dataset:pyfraug.Dataset, parallel:builtins.bool) -> None:
        r"""
        Augment a whole batch
        
        Parallelized when `parallell` is set
        """
    def augment_one(self, x:numpy.typing.NDArray[numpy.float64]) -> numpy.typing.NDArray[numpy.float64]:
        r"""
        Augment one time series
        
        When called, the augmenter will always augment the series no matter what the probability for this augmenter is
        """
    def set_probability(self, p:builtins.float) -> None:
        r"""
        By setting a probability with this function the augmenter will only augment
        a series in a batch with the specified probability
        """

class Rotation:
    r"""
    Augmenter that rotates the data 180 degrees around `anchor`
    """
    name: builtins.str
    probability: builtins.float
    def augment_batch(self, dataset:pyfraug.Dataset, parallel:builtins.bool) -> None:
        r"""
        Augment a whole batch
        
        Parallelized when `parallell` is set
        """
    def augment_one(self, x:numpy.typing.NDArray[numpy.float64]) -> numpy.typing.NDArray[numpy.float64]:
        r"""
        Augment one time series
        
        When called, the augmenter will always augment the series no matter what the probability for this augmenter is
        """
    def set_probability(self, p:builtins.float) -> None:
        r"""
        By setting a probability with this function the augmenter will only augment
        a series in a batch with the specified probability
        """

class Scaling:
    r"""
    Augmenter that scales a time series with a random scalar within the range specified
    by `min_factor` (inclusive) and `max_factor` (inclusive)
    """
    name: builtins.str
    probability: builtins.float
    def augment_batch(self, dataset:pyfraug.Dataset, parallel:builtins.bool) -> None:
        r"""
        Augment a whole batch
        
        Parallelized when `parallell` is set
        """
    def augment_one(self, x:numpy.typing.NDArray[numpy.float64]) -> numpy.typing.NDArray[numpy.float64]:
        r"""
        Augment one time series
        
        When called, the augmenter will always augment the series no matter what the probability for this augmenter is
        """
    def set_probability(self, p:builtins.float) -> None:
        r"""
        By setting a probability with this function the augmenter will only augment
        a series in a batch with the specified probability
        """

class ConvolveWindow(Enum):
    r"""
    Enum to specify the kernel window for the `Convolve` augmenter
    """
    Flat = ...
    Gaussian = ...

class NoiseType(Enum):
    r"""
    Enum to specify the noise type for the AddNoise augmenter
    """
    Uniform = ...
    Gaussian = ...
    Spike = ...
    Slope = ...

class PoolingMethod(Enum):
    r"""
    Enum to specify the pooling function for the `Pool` augmenter
    """
    Max = ...
    Min = ...
    Average = ...

